### ISSUE TITLE
Undefined variable (and other inconcsistencies)

### ISSUE THREAD

**Issue by ArkenV** [cerebrusinc/buncors#2]
I'm brand new to Bun's ecosystem, so I can't say if this is a new issue with buncors. Just in case, I'd like to point out some perceived bugs here.

Scenario one:

```js
import cors from 'buncors';
import server from 'bunrest';

const app = server();
app.use(cors());

app.post('/test', async (req, res) => {
  res.status(200).json(req.body);
})

app.listen(3000, () => {
  console.log("Server started on port 3000");
})
```

```bash
154 | 
155 |         const tree: TrieTree<string, Handler> =
156 |           that.requestMap[req.method.toLowerCase()];
157 | 
158 |         if (!tree) {
159 |           throw new Error(`There is no path matches ${req.method}`);
                      ^
error: There is no path matches OPTIONS
      at /Users/dannybetancourt/misc/node_modules/bunrest/src/server/server.ts:159:17
OPTIONS - /test failed
154 | 
155 |         const tree: TrieTree<string, Handler> =
156 |           that.requestMap[req.method.toLowerCase()];
157 | 
158 |         if (!tree) {
159 |           throw new Error(`There is no path matches ${req.method}`);
                      ^
error: There is no path matches OPTIONS
      at /Users/dannybetancourt/misc/node_modules/bunrest/src/server/server.ts:159:17
```

Scenario two:

```js
import cors from 'buncors';
import server from 'bunrest';

const app = server();

app.post('/test', cors(), async (req, res) => {
  res.status(200).json(req.body);
})

app.listen(3000, () => {
  console.log("Server started on port 3000");
})
```

Same outcome as the first scenario. Seems an options entry is required despite the documentation showing these two usages are allowed.

Scenario three:

```js
import cors from 'buncors';
import server from 'bunrest';

const app = server();

app.options(
	"/test",
	cors({
		origins: ["http://localhost:4200"]
	})
);

app.post('/test', async (req, res) => {
  res.status(200).json(req.body);
})

app.listen(3000, () => {
  console.log("Server started on port 3000");
})
```

```bash
119 |         return valid;
120 |     };
121 |     var _validReqHandler = function (res, resHeaders) {
122 |         switch (Array.isArray(origins)) {
123 |             case true:
124 |                 resHeaders["Access-Control-Allow-Origin"] = origin;
                                                                  ^
ReferenceError: Can't find variable: origin
      at _validReqHandler (/Users/dannybetancourt/misc/node_modules/buncors/lib/index.js:124:61)
      at middelware (/Users/dannybetancourt/misc/node_modules/buncors/lib/index.js:166:21)
      at /Users/dannybetancourt/misc/node_modules/bunrest/src/server/server.ts:204:26
OPTIONS - /test failed
119 |         return valid;
120 |     };
121 |     var _validReqHandler = function (res, resHeaders) {
122 |         switch (Array.isArray(origins)) {
123 |             case true:
124 |                 resHeaders["Access-Control-Allow-Origin"] = origin;
                                                                  ^
ReferenceError: Can't find variable: origin
      at _validReqHandler (/Users/dannybetancourt/misc/node_modules/buncors/lib/index.js:124:61)
      at middelware (/Users/dannybetancourt/misc/node_modules/buncors/lib/index.js:166:21)
      at /Users/dannybetancourt/misc/node_modules/bunrest/src/server/server.ts:204:26
```

It can't find this internal variable that's only used if `origins` is an array. If I instead make it a string to fail this check, I no longer get any crashes or error messages on the backend, but the frontend still claims:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/test. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`, despite somehow registering my status code of `200`.

Hardcoding it to `*` (the default value) shows the same behavior.

**Comment by ArkenV** [comment]
Unless I'm mistaken, it looks like the source is completely ignoring domains passed in as a string:

```ts
switch (Array.isArray(origins)) {
			case true:
				resHeaders["Access-Control-Allow-Origin"] = origin;
				res.setHeader("Access-Control-Allow-Origin", origin);

				resHeaders["Vary"] = "Accept-Encoding, Origin";
				res.setHeader("Vary", "Accept-Encoding, Origin");

				break;
			default:
				resHeaders["Access-Control-Allow-Origin"] = "*";
				res.setHeader("Access-Control-Allow-Origin", "*");
		}
```

**Comment by ArkenV** [comment]
The plot thickens...

So, this version of the code registers a successful round trip on the frontend:

```ts
import cors from 'buncors';
import server from 'bunrest';

const app = server();

app.options(
	"/test",
	cors({origins: ''})
);

app.post('/test', cors(), async (req, res) => {
  res.status(200).json(req.body);
})

app.listen(3000, () => {
  console.log("Server started on port 3000");
})
```

...but if I add anything at all in the string for origins, it breaks again. I haven't found why it matters if this string is empty or not. Then again, I hesitate to say it worked since we're initializing buncors in two different ways here and, as seen above, the domain is being ignored anyway.
